[2025-03-12T21:38:37.529+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T21:38:37.552+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.process_to_raw manual__2025-03-12T21:38:31.379553+00:00 [queued]>
[2025-03-12T21:38:37.565+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.process_to_raw manual__2025-03-12T21:38:31.379553+00:00 [queued]>
[2025-03-12T21:38:37.565+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-12T21:38:37.581+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): process_to_raw> on 2025-03-12 21:38:31.379553+00:00
[2025-03-12T21:38:37.587+0000] {standard_task_runner.py:72} INFO - Started process 186 to run task
[2025-03-12T21:38:37.591+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'process_to_raw', 'manual__2025-03-12T21:38:31.379553+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmpzl38txl3']
[2025-03-12T21:38:37.593+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask process_to_raw
[2025-03-12T21:38:37.619+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.10/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-12T21:38:37.682+0000] {task_command.py:467} INFO - Running <TaskInstance: data_lake_pipeline.process_to_raw manual__2025-03-12T21:38:31.379553+00:00 [running]> on host ***-scheduler
[2025-03-12T21:38:37.825+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='process_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T21:38:31.379553+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T21:38:31.379553+00:00'
[2025-03-12T21:38:37.828+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T21:38:37.843+0000] {manage_buckets.py:24} INFO - [Data manager] Downloading data from HuggingFace...
[2025-03-12T21:38:41.660+0000] {logging_mixin.py:190} WARNING - Generating test split:   0%|          | 0/4358 [00:00<?, ? examples/s]
[2025-03-12T21:38:41.724+0000] {logging_mixin.py:190} WARNING - Generating test split: 100%|##########| 4358/4358 [00:00<00:00, 69283.72 examples/s]
[2025-03-12T21:38:41.725+0000] {logging_mixin.py:190} WARNING - Generating train split:   0%|          | 0/36718 [00:00<?, ? examples/s]
[2025-03-12T21:38:41.830+0000] {logging_mixin.py:190} WARNING - Generating train split:  90%|########9 | 33000/36718 [00:00<00:00, 315407.91 examples/s]
[2025-03-12T21:38:41.838+0000] {logging_mixin.py:190} WARNING - Generating train split: 100%|##########| 36718/36718 [00:00<00:00, 327053.99 examples/s]
[2025-03-12T21:38:41.839+0000] {logging_mixin.py:190} WARNING - Generating validation split:   0%|          | 0/3760 [00:00<?, ? examples/s]
[2025-03-12T21:38:41.859+0000] {logging_mixin.py:190} WARNING - Generating validation split: 100%|##########| 3760/3760 [00:00<00:00, 198387.09 examples/s]
[2025-03-12T21:38:41.881+0000] {manage_buckets.py:27} INFO - [Data manager] Data successfully downloaded.
[2025-03-12T21:38:41.882+0000] {manage_buckets.py:30} INFO - [Data manager] Transferring data to S3 bucket...
[2025-03-12T21:38:41.883+0000] {aws_s3_repository.py:133} INFO - [AWS S3] Uploading into raw ...
[2025-03-12T21:38:41.884+0000] {aws_s3_repository.py:136} INFO - [AWS S3] Transferring train data...
[2025-03-12T21:38:41.884+0000] {aws_s3_repository.py:148} CRITICAL - [AWS S3] Error while uploading data into raw ...
[2025-03-12T21:38:41.885+0000] {manage_buckets.py:42} CRITICAL - [Data manager] Error during uploading files to S3 bucket named raw
[2025-03-12T21:38:41.885+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-12T21:38:41.908+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T21:38:41.910+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=process_to_raw, run_id=manual__2025-03-12T21:38:31.379553+00:00, execution_date=20250312T213831, start_date=20250312T213837, end_date=20250312T213841
[2025-03-12T21:38:41.980+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-12T21:38:42.022+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-12T21:38:42.027+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
